# Generated by Django 3.0.8 on 2020-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200709_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CL', 'CLIENT'), ('EX', 'EXPERT'), ('EM', 'EMPLOYEE')], default='CL', max_length=10),
        ),
    ]
